# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "7fd4084cee7e5030098702b3f13304c1"
application_url = "https://sporting-powerseller-florence-katrina.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://sporting-powerseller-florence-katrina.trycloudflare.com/auth/callback",
  "https://sporting-powerseller-florence-katrina.trycloudflare.com/auth/shopify/callback",
  "https://sporting-powerseller-florence-katrina.trycloudflare.com/api/auth/callback",
  "https://sporting-powerseller-florence-katrina.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-17.myshopify.com"
